# Generated by Django 5.2 on 2025-04-25 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actual',
            old_name='name',
            new_name='sheet_name',
        ),
        migrations.RemoveField(
            model_name='actual',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='actual',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='actual',
            name='start_date',
        ),
        migrations.AddField(
            model_name='archive',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
