# Generated by Django 5.2 on 2025-04-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_rename_name_actual_sheet_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='name',
            new_name='sheet_name',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='start_date',
        ),
    ]
