# Generated by Django 4.2.20 on 2025-04-26 10:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_rename_name_archive_sheet_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='actual',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='budget',
        ),
        migrations.AlterField(
            model_name='actual',
            name='sheet_name',
            field=models.CharField(max_length=50, verbose_name='Naam registratieblad'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('IN', 'Inkomen'), ('VAST', 'Vaste lasten'), ('FLEX', 'Flexibele lasten')], max_length=5, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Naam'),
        ),
        migrations.CreateModel(
            name='ArchiveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.archive')),
            ],
        ),
    ]
