# Generated by Django 4.2.20 on 2025-04-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_remove_archive_actual_remove_archive_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiverecord',
            name='category',
            field=models.CharField(choices=[('IN', 'Inkomen'), ('VAST', 'Vaste lasten'), ('FLEX', 'Flexibele lasten')], default='IN', max_length=5, verbose_name='Categorie'),
            preserve_default=False,
        ),
    ]
