# Generated by Django 4.2.20 on 2025-04-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_archiverecord_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiverecord',
            name='name',
            field=models.CharField(default='Placeholder', max_length=50, unique=True, verbose_name='Naam'),
            preserve_default=False,
        ),
    ]
